services:
  back-end:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Application:/Application
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.4.0-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./Application:/Application
    links:
      - redis
    depends_on:
      - redis
