services:
  back-end:
    build:
      context: ./Application/back-end/
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - ./Application/back-end:/Application/back-end
    command: gunicorn RuVideo.wsgi:application --bind 0.0.0.0:8000

  redis:
    image: redis:7.4.0-alpine
    hostname: redis

  worker:
    build:
      context: ./Application/back-end/
      dockerfile: Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./Application/back-end:/Application/back-end
    links:
      - redis
    depends_on:
      - redis


  nginx:
    restart: always
    build:
      context: ./Application/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - back-end
#      - front-end
    volumes:
      - ./Application/back-end/static:/etc/nginx/static
      - ./Application/back-end/media:/etc/nginx/media
